import type { CebuGuideItem } from "./cebuPlacesData";
import type { MassageQuality, MassageRecommend, MassageZone } from "./massageFilters";
import {
  googleMapsPlaceSearchUrl,
  googleMapsSearchUrl,
  normalizeCebuLatLng,
  parseShopDisplayName,
} from "./mapCoords";

/** 막탄 마사지샵 공통 데이터 규격 */
export type MactanMassageShop = {
  name: string;
  lat: number;
  lng: number;
  desc: string;
  mapsQuery?: string;
  placeId?: string;
  quality?: MassageQuality;
  zones?: MassageZone[];
  recommends?: MassageRecommend[];
  rating?: string;
  openingHours?: string;
  priceLevel?: string;
  reservationUrl?: string;
  blogUrl?: string;
};
const MASSAGE_IDS = [
  "massage-oasis-spa",
  "massage-cielo-spa",
  "massage-kakao-tree",
  "massage-baan-newtown",
  "massage-amoa",
  "massage-velspa",
  "massage-sen-spa",
  "massage-lugari",
  "massage-eco-spa",
  "massage-nuathai-mactan",
  "massage-phytoncide",
  "massage-nu-spa",
  "massage-kt-cebu",
  "massage-funwe",
  "massage-nature-wellness",
  "massage-top-spa-nail",
  "massage-raon-square",
  "massage-hua-villa",
  "massage-king-spa",
  "massage-cebu-glory",
  "massage-soleil",
  "massage-raum",
  "massage-mir",
  "massage-yuri-maribago",
  "massage-spa-world",
  "massage-baan-maribago-savemore",
  "massage-baan-maribago",
  "massage-flower-tree",
  "massage-siwon",
  "massage-cebu-spa-in",
  "massage-shima-spa",
  "massage-the-thai",
  "massage-lara",
  "massage-again",
  "massage-goldmoon",
  "massage-arnika",
  "massage-cheava",
  "massage-banyan-lounge",
  "massage-l-spa",
  "massage-kannawa",
  "massage-green",
  "massage-nuathai-marigondon",
  "massage-iah",
  "massage-cient-thai",
  "massage-thai-boran",
  "massage-thai-nature-garden",
  "massage-ocean",
  "massage-treeshade",
] as const;

/** 막탄 마사지샵 전체 */
export const MACTAN_MASSAGE_SHOPS: MactanMassageShop[] = [
  {
    name: "오아시스 스파 (Oasis Spa)",
    lat: 10.311342290288357,
    lng: 124.01857160021163,
    desc: "샹그릴라 리조트 인근 더 프롬나드 막탄에 위치한 스파입니다. 해피아워 특가 및 당일 예약이 가능하며, 깔끔한 시설과 안정적인 실력으로 입소문난 곳입니다.",
    rating: "⭐ 4.5",
    openingHours: "매일 10:00 - 23:00",
    priceLevel: "₱₱₱",
    quality: "고급",
    zones: ["샹그릴라 주변"],
    recommends: ["도착 첫날", "출국 전", "호핑 후", "커플", "부모님", "픽업드랍"],
    reservationUrl:
      "https://pf.kakao.com/_xoVxhjxb/chat?utm_source=cebu-places-app&utm_medium=massage&utm_campaign=oasis-spa",
  },
  {
    name: "치엘로 스파 (Cielo Spa)",
    lat: 10.311848956789763,
    lng: 124.02297042297324,
    desc: "고급스러운 인테리어와 VIP룸을 갖춘 프리미엄 스파입니다. 미니 정원과 커피숍이 함께 운영되어 마사지 전후 여유로운 시간을 보낼 수 있습니다. 제이파크 리조트에서 5분 거리에 위치하며, 친절한 한국어 안내로 편안하게 이용할 수 있습니다.",
    rating: "⭐ 4.9",
    openingHours: "매일 10:00 - 00:00",
    priceLevel: "₱₱₱",
    quality: "고급",
    zones: ["샹그릴라 주변"],
    recommends: ["호핑 후", "커플", "부모님", "픽업드랍"],
    reservationUrl:
      "https://pf.kakao.com/_xoVxhjxb/chat?utm_source=cebu-places-app&utm_medium=massage&utm_campaign=cielo-spa",
  },
  {
    name: "카카오트리스파 (Cacao Tree Spa)",
    lat: 10.31085673405128,
    lng: 124.02224086215053,
    desc: "샹그릴라 근처에 위치한 한국인 사장님 운영 스파입니다. 해피아워 특가와 당일 예약이 가능해 일정이 급하게 바뀌어도 편하게 이용할 수 있습니다.",
    rating: "⭐ 4.7",
    openingHours: "매일 10:00 - 22:00",
    priceLevel: "₱₱₱",
    quality: "고급",
    zones: ["샹그릴라 주변"],
    recommends: ["도착 첫날", "출국 전", "커플", "픽업드랍"],
    reservationUrl: "https://myrealt.rip/bnu5b9",
  },
  {
    name: "바안스파 앤 네일 뉴타운점 (Baan Spa & Nail Newtown)",
    lat: 10.308043859005956,
    lng: 124.01365042412483,
    desc: "막탄 뉴타운 중심에 위치한 마사지와 네일을 동시에 즐길 수 있는 복합 스파입니다. 뉴타운 쇼핑·식사 후 바로 방문하기 좋은 접근성을 자랑하며, 꼼꼼한 네일 아트와 편안한 마사지를 합리적인 가격에 제공합니다.",
    rating: "⭐ 4.3",
    openingHours: "매일 10:30 - 01:00",
    priceLevel: "₱₱",
    quality: "고급",
    zones: ["뉴타운 주변"],
    recommends: ["출국 전"],
  },
  {
    name: "세부 아모아 스파 (Amoa Spa)",
    lat: 10.316231913671723,
    lng: 124.02783677075777,
    desc: "샹그릴라 리조트 인근에 위치한 스파입니다. 합리적인 가격에 편안한 마사지를 즐길 수 있어 출국 전 방문하기 좋은 곳입니다.",
    rating: "⭐ 4.6",
    openingHours: "매일 13:00 - 23:30",
    quality: "중저가",
    zones: ["샹그릴라 주변"],
    recommends: ["출국 전"],
  },
  {
    name: "벨 스파 (VELSPA)",
    lat: 10.313152239646707,
    lng: 124.0237576491916,
    desc: "샹그릴라 리조트 인근 푼타엔냐오 로드에 위치한 스파입니다. 합리적인 가격에 편안한 케어를 받을 수 있으며, 커플·가족 방문객에게 인기 있는 곳입니다.",
    quality: "중저가",
    zones: ["샹그릴라 주변"],
    recommends: ["출국 전", "커플", "부모님"],
    rating: "⭐ 4.7",
    openingHours: "매일 10:00 - 00:00",
  },
  {
    name: "쎈스파",
    lat: 10.3075896,
    lng: 124.0097644,
    desc: "LG Garden Walk, M.L. Quezon National Highway, Lapu-Lapu 6015 · 가성비 좋고 시원한 압으로 입소문 난 곳",
    rating: "⭐ 4.8",
    openingHours: "매일 10:00 - 23:50",
    priceLevel: "₱₱",
    mapsQuery: "쎈스파ssen spa",
    placeId: "ChIJFfW64qOaqTMR_V5F706Vp1w",
    quality: "중저가",
    zones: ["뉴타운 주변"],
    recommends: ["출국 전"],
  },
  {
    name: "루가리 마사지",
    lat: 10.307304,
    lng: 124.009476,
    desc: "키즈카페를 함께 운영하는 루가리 스파입니다. 픽업·마사지·공항 드랍까지 한 번에 가능해 가족 여행객에게 특히 편리합니다.",
    quality: "중저가",
    zones: ["뉴타운 주변"],
    recommends: ["출국 전", "커플", "부모님"],
    reservationUrl: "https://myrealt.rip/boRC44",
  },
  {
    name: "에코스파",
    lat: 10.310102,
    lng: 123.999563,
    desc: "자연 친화적인 분위기 속에서 편안한 케어를 받을 수 있는 스파입니다. 아로마 오일과 천연 재료를 활용한 테라피로 몸과 마음의 피로를 동시에 풀어줍니다. 가든워크 인근에 위치해 접근성이 뛰어납니다.",
    rating: "⭐ 4.0",
    openingHours: "매일 09:00 - 23:00",
    priceLevel: "₱₱",
    quality: "고급",
    zones: ["샹그릴라 주변"],
    recommends: ["출국 전", "호핑 후", "커플", "부모님", "픽업드랍"],
    reservationUrl:
      "https://pf.kakao.com/_xoVxhjxb/chat?utm_source=cebu-places-app&utm_medium=massage&utm_campaign=eco-spa",
    blogUrl: "https://m.blog.naver.com/aalove0902/223705706206",
  },
  {
    name: "누앗타이 막탄",
    lat: 10.306977,
    lng: 124.010045,
    desc: "필리핀 대표 로컬 마사지 브랜드의 막탄 지점",
    rating: "⭐ 4.5",
    openingHours: "매일 10:00 - 23:00",
    priceLevel: "₱₱",
    quality: "중저가",
    zones: ["뉴타운 주변"],
    recommends: ["출국 전"],
  },
  {
    name: "피톤치드",
    lat: 10.306497,
    lng: 124.009195,
    desc: "상쾌한 피톤치드 향과 깔끔한 인테리어가 인상적인 스파입니다. 산림욕 효과를 접목한 테라피로 세부 여행 중 특별한 힐링 경험을 선사합니다. 가든워크 인근에 위치해 투어 후 편하게 들르기 좋습니다.",
    rating: "⭐ 5.0",
    openingHours: "매일 10:00 - 23:30",
    priceLevel: "₱₱",
    quality: "중저가",
    zones: ["뉴타운 주변"],
    recommends: ["출국 전"],
  },
  {
    name: "누스파",
    lat: 10.306837,
    lng: 124.008571,
    desc: "세부 프리미엄 마사지샵으로 해피아워 90분 특가(23,900원)로 유명합니다. 가성비 좋은 마사지를 찾는 분께 추천합니다.",
    rating: "⭐ 4.8",
    openingHours: "매일 10:00 - 23:00",
    priceLevel: "₱₱",
    quality: "중저가",
    zones: ["뉴타운 주변"],
    recommends: ["호핑 후", "커플", "부모님", "픽업드랍"],
    reservationUrl: "https://myrealt.rip/bnxu84",
  },
  {
    name: "KT세부스파",
    lat: 10.305914,
    lng: 124.009426,
    desc: "자유여행객들이 편하게 들르기 좋은 접근성",
    rating: "⭐ 4.7",
    openingHours: "매일 12:00 - 00:00",
    priceLevel: "₱₱",
    quality: "중저가",
    zones: ["뉴타운 주변"],
    recommends: ["출국 전"],
  },
  {
    name: "펀웨 스파",
    lat: 10.30576,
    lng: 124.009136,
    desc: "부담 없는 가격에 시원한 마사지를 제공하는 곳",
    rating: "⭐ 4.6",
    openingHours: "매일 10:00 - 03:00",
    priceLevel: "₱",
    quality: "중저가",
    zones: ["뉴타운 주변"],
    recommends: ["출국 전"],
  },
  {
    name: "네이처 웰니스 마사지앤스파",
    lat: 10.304324,
    lng: 124.007634,
    desc: "웰니스를 모티브로 한 힐링 테라피 스파",
    rating: "⭐ 4.6",
    openingHours: "매일 13:00 - 00:00",
    priceLevel: "₱₱",
    quality: "중저가",
    zones: ["뉴타운 주변"],
    recommends: ["출국 전"],
  },
  {
    name: "탑스파&탑네일",
    lat: 10.301338,
    lng: 124.011306,
    desc: "막탄 크림슨·더리프 리조트 근처에 위치한 프리미엄 마사지샵입니다. 0.5박 수면팩과 무료 공항 픽업 서비스를 함께 제공해 늦은 입출국 일정에도 유용합니다.",
    rating: "⭐ 4.8",
    openingHours: "매일 10:30 - 01:00",
    priceLevel: "₱₱",
    quality: "중저가",
    zones: ["뉴타운 주변"],
    recommends: ["도착 첫날", "출국 전", "호핑 후", "커플", "부모님", "픽업드랍"],
    reservationUrl: "https://myrealt.rip/bnzafb",
  },
  {
    name: "라온스퀘어",
    lat: 10.300467,
    lng: 124.008734,
    desc: "스파와 문화 공간이 어우러진 막탄 대형 프리미엄 스파 시설입니다. 넓고 고급스러운 공간에서 다양한 테라피 프로그램을 즐길 수 있으며, 커플·가족 단위 방문객에게 특히 인기가 높습니다. 세부 여행 중 특별한 날을 기념하기 좋은 프리미엄 스파입니다.",
    rating: "⭐ 4.4",
    openingHours: "매일 10:00 - 23:00",
    priceLevel: "₱₱₱",
    quality: "고급",
    zones: ["뉴타운 주변"],
    recommends: ["도착 첫날", "출국 전", "커플"],
  },
  {
    name: "후아스파& 빌라",
    lat: 10.299594,
    lng: 124.003345,
    desc: "빌라 스타일의 프라이빗하고 고급스러운 마사지",
    rating: "⭐ 4.0",
    openingHours: "매일 10:00 - 23:00",
    priceLevel: "₱₱₱",
    quality: "고급",
    zones: ["샹그릴라 주변"],
    recommends: ["출국 전"],
  },
  {
    name: "킹스파",
    lat: 10.295222,
    lng: 123.998835,
    desc: "막탄 최대 규모를 자랑하는 스파로, 한국인 매니저가 상주하고 샤워 시설까지 완비되어 있습니다. 해피아워 특가와 당일 예약이 가능합니다.",
    rating: "⭐ 4.4",
    openingHours: "매일 10:00 - 23:45",
    priceLevel: "₱₱₱",
    quality: "고급",
    zones: ["마리바고 주변"],
    recommends: ["호핑 후", "커플", "부모님", "픽업드랍"],
    reservationUrl: "https://myrealt.rip/bnuy8b",
  },
  {
    name: "세부글로리스파",
    lat: 10.295221,
    lng: 123.998418,
    desc: "여행의 시작이나 마무리에 들르기 좋은 쾌적한 스파입니다. 합리적인 가격에 깔끔한 시설과 친절한 서비스를 제공하며, 마리바고 리조트 투숙객들이 호핑투어 후 자주 찾는 곳입니다.",
    rating: "⭐ 4.8",
    openingHours: "매일 10:00 - 23:00",
    priceLevel: "₱₱",
    quality: "중저가",
    zones: ["마리바고 주변"],
    recommends: ["출국 전"],
  },
  {
    name: "솔레일 스파",
    lat: 10.292576,
    lng: 123.998223,
    desc: "정성스러운 케어로 여행자 피로 회복에 제격",
    rating: "⭐ 4.3",
    openingHours: "매일 12:00 - 00:00",
    priceLevel: "₱₱",
    quality: "중저가",
    zones: ["마리바고 주변"],
    recommends: ["출국 전"],
  },
  {
    name: "라움스파",
    lat: 10.290078,
    lng: 123.997239,
    desc: "감성적인 인테리어와 디테일한 케어가 돋보이는 프리미엄 스파입니다. 아로마 향이 가득한 공간에서 숙련된 테라피스트의 정성 어린 마사지를 받을 수 있습니다. 커플 패키지와 스페셜 케어 프로그램이 잘 갖춰져 있어 특별한 날 방문하기 좋습니다.",
    rating: "⭐ 4.8",
    openingHours: "매일 11:00 - 23:30",
    priceLevel: "₱₱₱",
    quality: "고급",
    zones: ["마리바고 주변"],
    recommends: ["출국 전", "호핑 후", "커플", "부모님", "픽업드랍"],
    reservationUrl:
      "https://pf.kakao.com/_xoVxhjxb/chat?utm_source=cebu-places-app&utm_medium=massage&utm_campaign=raum-spa",
  },
  {
    name: "미르스파",
    lat: 10.29013,
    lng: 123.998752,
    desc: "여행객들의 입소문을 타고 인기를 끄는 마사지샵",
    rating: "⭐ 4.7",
    openingHours: "매일 11:00 - 23:30",
    priceLevel: "₱₱",
    quality: "중저가",
    zones: ["마리바고 주변"],
    recommends: ["출국 전"],
  },
  {
    name: "유리스파마리바고",
    lat: 10.287882,
    lng: 123.999149,
    desc: "마리바고 중심가에서 편하게 들를 수 있는 스파",
    rating: "⭐ 4.1",
    openingHours: "매일 10:00 - 00:00",
    priceLevel: "₱₱",
    quality: "중저가",
    zones: ["마리바고 주변"],
    recommends: ["출국 전"],
  },
  {
    name: "스파월드",
    lat: 10.287259,
    lng: 123.997862,
    desc: "넓은 시설과 다양한 마사지 코스를 보유한 대형 스파입니다. 타이·아로마·스톤 등 다양한 코스 중 원하는 테라피를 선택할 수 있으며, 마리바고 지역에서 접근성이 좋아 호핑투어 후 방문하기 편리합니다. 단체·가족 방문객도 여유롭게 이용 가능한 규모입니다.",
    rating: "⭐ 4.9",
    openingHours: "매일 00:00 - 00:00 (24시간)",
    priceLevel: "₱₱",
    quality: "고급",
    zones: ["마리바고 주변"],
    recommends: ["출국 전", "호핑 후", "커플", "부모님", "픽업드랍"],
    reservationUrl: "https://myrealt.rip/bnwq04",
  },
  {
    name: "바안스파 마리바고세이브모어",
    lat: 10.286467,
    lng: 123.997508,
    desc: "세이브모어 쇼핑 후 방문하기 딱 좋은 위치의 스파",
    rating: "⭐ 4.7",
    openingHours: "매일 10:00 - 00:00",
    priceLevel: "₱₱",
    quality: "중저가",
    zones: ["마리바고 주변"],
    recommends: ["출국 전"],
  },
  {
    name: "바안스파 마리바고",
    lat: 10.286098,
    lng: 123.998076,
    desc: "마리바고 리조트 구역 여행객들에게 꾸준히 사랑받는 곳",
    rating: "⭐ 4.5",
    openingHours: "매일 10:00 - 00:00",
    priceLevel: "₱₱",
    quality: "중저가",
    zones: ["마리바고 주변"],
    recommends: ["출국 전"],
  },
  {
    name: "플라워트리스파",
    lat: 10.286174,
    lng: 123.997914,
    desc: "아기자기한 분위기와 친절한 테라피스트가 있는 샵",
    rating: "⭐ 4.3",
    openingHours: "24시간 영업",
    priceLevel: "₱₱",
    quality: "중저가",
    zones: ["마리바고 주변"],
    recommends: ["출국 전"],
  },
  {
    name: "시원스파",
    lat: 10.286003,
    lng: 123.997036,
    desc: "뭉친 근육을 시원하게 풀어주는 가이드 추천 스파",
    rating: "⭐ 4.4",
    openingHours: "매일 13:00 - 00:00",
    priceLevel: "₱₱",
    quality: "중저가",
    zones: ["마리바고 주변"],
    recommends: ["출국 전"],
  },
  {
    name: "세부 스파인",
    lat: 10.284198,
    lng: 123.994868,
    desc: "체형과 척추 밸런스에 집중한 전문적인 테라피 샵",
    rating: "⭐ 5.0",
    openingHours: "매일 10:00 - 01:00",
    priceLevel: "₱₱",
    quality: "고급",
    zones: ["마리바고 주변"],
    recommends: ["출국 전"],
  },
  {
    name: "시마스파",
    lat: 10.283865487511157,
    lng: 123.99485707399901,
    desc: "마리바고 일대에서 접근하기 좋은 스파",
    rating: "⭐ 4.2",
    openingHours: "매일 11:00 - 00:00",
    priceLevel: "₱₱",
    mapsQuery: "시마스파",
    quality: "중저가",
    zones: ["마리바고 주변"],
    recommends: ["출국 전"],
  },
  {
    name: "더타이",
    lat: 10.283461,
    lng: 123.993757,
    desc: "전통 타이 마사지의 손맛을 제대로 느낄 수 있는 곳",
    rating: "⭐ 4.5",
    openingHours: "매일 - 23:00",
    priceLevel: "₱₱",
    quality: "중저가",
    zones: ["마리바고 주변"],
    recommends: ["출국 전"],
  },
  {
    name: "라라스파",
    lat: 10.283779,
    lng: 123.99368,
    desc: "가성비와 실력을 모두 잡아 부담 없이 방문하는 스파",
    rating: "⭐ 4.2",
    openingHours: "매일 10:00 - 22:00",
    priceLevel: "₱₱",
    quality: "중저가",
    zones: ["마리바고 주변"],
    recommends: ["출국 전"],
  },
  {
    name: "어게인스파",
    lat: 10.282961,
    lng: 123.993285,
    desc: "세부 여행 중 재방문율이 높은 아늑한 마사지샵",
    rating: "⭐ 4.8",
    openingHours: "매일 10:00 - 01:00",
    priceLevel: "₱₱",
    quality: "중저가",
    zones: ["마리바고 주변"],
    recommends: ["출국 전"],
  },
  {
    name: "골드문스파",
    lat: 10.282617,
    lng: 123.992936,
    desc: "세부 골드문 스파 막탄지점입니다. 재방문율이 높은 인기 스파로, 막탄 내 픽업·드랍 서비스도 함께 이용할 수 있습니다.",
    rating: "⭐ 4.7",
    openingHours: "매일 10:00 - 00:00",
    priceLevel: "₱₱₱",
    quality: "고급",
    zones: ["마리바고 주변"],
    recommends: ["출국 전", "호핑 후", "커플", "부모님", "픽업드랍"],
    reservationUrl: "https://myrealt.rip/bnyg13",
  },
  {
    name: "아니카 스파 (Arnika Spa Therapy Cebu)",
    lat: 10.287494347962056,
    lng: 123.99159726694074,
    desc: "제이파크 리조트 인근에 위치한 고급 스파입니다. 전문 테라피스트의 체계적인 케어로 여행의 피로를 풀기 좋으며, 커플·가족 방문객에게 인기 있는 곳입니다.",
    quality: "고급",
    zones: ["마리바고 주변"],
    recommends: ["출국 전", "커플", "부모님", "픽업드랍"],
    rating: "⭐ 4.5",
    openingHours: "매일 10:00 - 23:00",
  },
  {
    name: "체아바 스파 (Cheava Spa Mactan)",
    lat: 10.284595328546844,
    lng: 123.9949034957759,
    desc: "마리바고 지역에 위치한 스파입니다. 높은 평점과 많은 리뷰 수가 증명하는 검증된 마사지샵으로, 숙련된 테라피스트의 꼼꼼한 케어를 합리적인 가격에 즐길 수 있습니다.",
    quality: "중저가",
    zones: ["마리바고 주변"],
    recommends: ["출국 전", "커플", "부모님"],
    rating: "⭐ 4.8",
    openingHours: "매일 11:00 - 02:00",
  },
  {
    name: "반얀 스파 & 라운지",
    lat: 10.317135,
    lng: 123.978157,
    desc: "고급 리조트 스파 감성의 인테리어와 라운지 시설 완비",
    rating: "⭐ 3.8",
    openingHours: "24시간 영업",
    priceLevel: "₱₱₱₱",
    quality: "중저가",
    zones: ["공항 주변"],
    recommends: ["커플", "부모님"],
  },
  {
    name: "엘스파",
    lat: 10.324587,
    lng: 123.977363,
    desc: "세부 3대 스파 중 하나로 막탄 공항 바로 인근에 위치한 명품 스파입니다. 매일 09:00~05:00 운영하며 공항 드랍 서비스를 제공해 출국 당일 마지막 코스로 최적입니다. 아로마·타이·스톤 등 다양한 테라피와 함께 공항 픽업+마사지+수면+조식 패키지도 운영합니다. 구글 평점 4.4점의 검증된 실력으로 재방문 고객이 특히 많습니다.",
    rating: "⭐ 4.6",
    openingHours: "매일 09:00 - 05:00 (익일)",
    priceLevel: "₱₱₱",
    quality: "중저가",
    zones: ["공항 주변"],
    recommends: ["도착 첫날", "출국 전", "커플", "부모님", "픽업드랍"],
    reservationUrl:
      "https://pf.kakao.com/_xoVxhjxb/chat?utm_source=cebu-places-app&utm_medium=massage&utm_campaign=el-spa",
    blogUrl: "https://m.blog.naver.com/aalove0902/223108541404",
  },
  {
    name: "칸나와 웰니스 스파",
    lat: 10.322222,
    lng: 123.97584,
    desc: "정교한 테라피 프로그램으로 몸을 제대로 리프레시",
    rating: "⭐ 4.6",
    openingHours: "매일 12:00 - 23:00",
    priceLevel: "₱₱₱",
    quality: "중저가",
    zones: ["공항 주변"],
    recommends: ["출국 전"],
  },
  {
    name: "그린스파",
    lat: 10.275357,
    lng: 123.97617,
    desc: "깔끔하고 쾌적한 환경에서 가볍게 피로 풀기 좋은 곳",
    rating: "⭐ 4.4",
    openingHours: "매일 15:00 - 00:00",
    priceLevel: "₱₱",
    quality: "중저가",
    zones: ["기타"],
    recommends: ["출국 전"],
  },
  {
    name: "누앗타이 마리곤돈",
    lat: 10.273784,
    lng: 123.97623,
    desc: "마리곤돈 교차로 인근 실속파들을 위한 로컬 스파",
    rating: "⭐ 3.6",
    openingHours: "매일 12:00 - 02:00",
    priceLevel: "₱₱",
    quality: "중저가",
    zones: ["기타"],
    recommends: ["출국 전"],
  },
  {
    name: "IAH마사지",
    lat: 10.27234,
    lng: 123.979255,
    desc: "현지 느낌 물씬 풍기는 숨은 마사지 맛집",
    rating: "⭐ 2.9",
    openingHours: "24시간 영업",
    priceLevel: "₱",
    quality: "중저가",
    zones: ["기타"],
    recommends: ["출국 전"],
  },
  {
    name: "시엔트 타이 스파 마사지",
    lat: 10.274651,
    lng: 123.975237,
    desc: "태국 전통 스타일의 압을 선호하는 분들에게 추천",
    rating: "⭐ 4.5",
    openingHours: "매일 13:00 - 02:00",
    priceLevel: "₱₱",
    quality: "중저가",
    zones: ["기타"],
    recommends: ["출국 전"],
  },
  {
    name: "타이보란",
    lat: 10.256736,
    lng: 123.959741,
    desc: "오랜 전통의 테라피 노하우를 가진 가성비 로컬 샵",
    rating: "⭐ 4.3",
    openingHours: "매일 12:00 - 00:00",
    priceLevel: "₱",
    quality: "중저가",
    zones: ["기타"],
    recommends: ["출국 전"],
  },
  {
    name: "타이 네이쳐 가든",
    lat: 10.256965,
    lng: 123.955444,
    desc: "초록빛 정원 분위기 속에서 조용하게 즐기는 스파",
    rating: "⭐ 4.5",
    openingHours: "매일 10:00 - 00:00",
    priceLevel: "₱",
    quality: "중저가",
    zones: ["기타"],
    recommends: ["출국 전"],
  },
  {
    name: "오션마사지 (Ocean Massage)",
    lat: 10.286339130721446,
    lng: 123.97004503833769,
    desc: "공항 인근에 위치한 오션스파로, 귀국팩·출국팩이 잘 갖춰져 있습니다. 숙소 픽업, 짐 보관, 90분 스톤 마사지, 룸 휴식, 공항 샌딩, 샤워용품까지 한 번에 해결할 수 있어 출국 당일 마지막 코스로 최적입니다.",
    rating: "⭐ 4.5",
    openingHours: "24시간 영업",
    quality: "중저가",
    zones: ["기타"],
    recommends: ["도착 첫날", "출국 전", "커플"],
    reservationUrl: "https://myrealt.rip/boPo7a",
  },
  {
    name: "트리쉐이드 스파 (Tree Shade Spa)",
    lat: 10.320645180726686,
    lng: 123.90310771929316,
    desc: "세부 최대 규모 한국인 직영 스파로, 공항 샌딩 서비스를 제공합니다. 아얄라몰까지 10분, 야시장까지 5분 거리로 위치가 좋아 해피아워 특가와 당일 예약도 가능합니다.",
    quality: "고급",
    zones: ["기타"],
    recommends: ["도착 첫날", "출국 전", "커플", "부모님"],
    reservationUrl: "https://myrealt.rip/boPxfb",
  },
];

function toGuideItem(shop: MactanMassageShop, id: string): CebuGuideItem {
  const { lat, lng } = normalizeCebuLatLng(Number(shop.lat), Number(shop.lng));
  const displayName = parseShopDisplayName(shop.name);
  const item: CebuGuideItem & { placeId?: string } = {
    id,
    title: shop.name,
    description: shop.desc,
    mapPin: { lat, lng },
    rating: shop.rating,
    openingHours: shop.openingHours,
  };
  if (shop.mapsQuery) item.mapsQuery = shop.mapsQuery;
  else if (!shop.blogUrl) item.mapsQuery = `${displayName} Mactan Cebu spa`;
  if (shop.placeId) item.placeId = shop.placeId;
  if (shop.quality) item.quality = shop.quality;
  if (shop.zones) item.zones = shop.zones;
  if (shop.recommends) item.recommends = shop.recommends;
  if (shop.reservationUrl) item.reservationUrl = shop.reservationUrl;
  if (shop.blogUrl) {
    item.mapPopupLink = {
      url: shop.blogUrl,
      label: "자세히 보기",
    };
  }
  if (!shop.blogUrl) {
    if (shop.mapsQuery && shop.placeId) {
      item.googleMapsUrl = googleMapsPlaceSearchUrl(shop.mapsQuery, shop.placeId);
    } else {
      item.googleMapsUrl = googleMapsSearchUrl(displayName);
    }
  }
  return item;
}

/** 막탄 마사지샵 가이드 아이템 */
export const MACTAN_MASSAGE_ITEMS: CebuGuideItem[] = MACTAN_MASSAGE_SHOPS.map((shop, i) =>
  toGuideItem(shop, MASSAGE_IDS[i]!),
);
